Repository Ludeon/RimWorld-PortugueseBrazilian, pull requests merged in 2021-07, with the labels that each got.

#120 Correção de identação e melhorias no BOASPRATICAS
  Core/LanguageInfo.xml
  README.md
  boaspraticas.md
Labels: enhancement

#126 Quick Updates + Bugs Fixing
  Core/DefInjected/BeardDef/BeardDefs.xml
  Core/DefInjected/HediffDef/Hediffs_Local_Misc.xml
  Core/DefInjected/HistoryEventDef/GoodwillEvents_Diplomatic.xml
  Core/DefInjected/InstructionDef/Instructions.xml
  Core/DefInjected/IssueDef/Precepts_Corpses.xml
  Core/DefInjected/PreceptDef/Precepts_InsectMeat.xml
  Core/DefInjected/QuestScriptDef/Scripts_JoinerThreatCore.xml
  Core/DefInjected/RecipeDef/ImpliedDefs.xml
  Core/DefInjected/RulePackDef/Places.xml
  Core/DefInjected/ThingDef/Apparel_Headgear.xml
  Core/DefInjected/ThingDef/Apparel_Various.xml
  Core/DefInjected/ThingDef/Hediffs_BodyParts_Bionic.xml
  Core/DefInjected/ThingDef/Mote_Meta.xml
  Core/DefInjected/ThingDef/Mote_MetaStatus.xml
  Core/DefInjected/ThingDef/Mote_Special.xml
  Core/DefInjected/ThingDef/Mote_Visual.xml
  Core/DefInjected/ThingDef/Mote_Water.xml
  Core/DefInjected/ThingDef/Races_Animal_CatGroup.xml
  Core/DefInjected/ThingDef/Races_Animal_CowGroup.xml
  Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
  Core/DefInjected/ThoughtDef/Thoughts_Situation_Social.xml
  Core/DefInjected/ThoughtDef/Thoughts_Situation_Traits.xml
  Core/DefInjected/TraitDef/Traits_Singular.xml
  Core/Keyed/Credits.xml
  Core/Keyed/Dialog_StatsReports.xml
  Core/Keyed/Dialogs_Various.xml
  Core/Keyed/Messages.xml
  Core/Keyed/Misc_Gameplay.xml
  Royalty/DefInjected/PreceptDef/Precepts_Ritual.xml
  Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
  Royalty/DefInjected/QuestScriptDef/Scripts_Permits.xml
  Royalty/DefInjected/RitualBehaviorDef/Ritual_Behaviors.xml
  Royalty/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
  Royalty/DefInjected/RulePackDef/Faction_Empire.xml
  Royalty/DefInjected/ThingDef/Mote_Visual.xml
  Royalty/DefInjected/ThingDef/ThingStyleDef.xml
  Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Rituals.xml
  Royalty/Keyed/GameplayCommands.xml
  Royalty/Keyed/Messages.xml
  Royalty/Keyed/Misc_Gameplay.xml
Labels: bug

#140 Correção
  Royalty/DefInjected/ThingDef/MeleeBladelink.xml
  Royalty/DefInjected/ThingDef/MeleeUltratech.xml
Labels: Need Changes
