Repository Ludeon/RimWorld-PortugueseBrazilian, pull requests merged in 2021-09, with the labels that each got.

#209 RimWorld 1.3.3101
  Core/Backstories/Backstories.xml
  Core/DefInjected/BodyPartDef/BodyParts_General.xml
  Core/DefInjected/HediffDef/Hediffs_BodyParts_Bionic.xml
  Core/DefInjected/HistoryEventDef/HistoryEventDefs.xml
  Core/DefInjected/RecipeDef/Hediffs_BodyParts_Bionic.xml
  Core/DefInjected/RulePackDef/RulePacks_Art_ImagesTaleless.xml
  Core/DefInjected/StatCategoryDef/StatCategories.xml
  Core/DefInjected/ThingDef/Buildings_Joy.xml
  Core/DefInjected/ThingDef/Hediffs_BodyParts_Bionic.xml
  Core/Keyed/Dialog_StatsReports.xml
  Core/Keyed/Menu_Options.xml
  Core/Keyed/Misc_Gameplay.xml
  Core/Strings/Names/WorldFeatures/Archipelagos_America.txt
  Core/Strings/Names/WorldFeatures/Bays_USA.txt
  Core/Strings/Names/WorldFeatures/ColdDeserts_NorthAmerica.txt
  Core/Strings/Names/WorldFeatures/Forests_USA.txt
  Core/Strings/Names/WorldFeatures/HotDeserts_NorthAmerica.txt
  Core/Strings/Names/WorldFeatures/HotDeserts_SouthAmerica.txt
  Core/Strings/Names/WorldFeatures/HotDeserts_World.txt
  Core/Strings/Names/WorldFeatures/Islands_Canada.txt
  Core/Strings/Names/WorldFeatures/Islands_USA.txt
  Core/Strings/Names/WorldFeatures/Lakes_Canada.txt
  Core/Strings/Names/WorldFeatures/Lakes_USA.txt
  Core/Strings/Names/WorldFeatures/MountainRanges_Canada.txt
  Core/Strings/Names/WorldFeatures/MountainRanges_USA.txt
  Core/Strings/Names/WorldFeatures/Oceans.txt
  Core/Strings/Names/WorldFeatures/Peninsulas_Canada.txt
  Core/Strings/Names/WorldFeatures/Plateaus_USA.txt
  Core/Strings/Names/WorldFeatures/Seas_America.txt
  Core/Strings/Names/WorldFeatures/Seas_World.txt
  Core/Strings/Names/WorldFeatures/Swamps_USA.txt
  Ideology/DefInjected/HistoryEventDef/Precepts_Proselytizing.xml
  Ideology/DefInjected/HistoryEventDef/Precepts_Ranching.xml
  Ideology/DefInjected/HistoryEventDef/Precepts_Trees.xml
  Ideology/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
Labels: Tipo: Erro, Tipo: Atualização do RimWorld, tamanho/G, Condição: Aguardando Revisão

#210 Bug Correction
  Core/DefInjected/ResearchProjectDef/ResearchProjects_3_Microelectronics.xml
  Core/DefInjected/RulePackDef/RulePacks_CombatRanged.xml
Labels: Tipo: Erro, tamanho/P, Condição: Aguardando Revisão

#211 Bug Correction - Biosculpter
  Ideology/DefInjected/IssueDef/Precepts_Transhumanism.xml
  Ideology/Keyed/Misc_Gameplay.xml
Labels: Tipo: Erro, Resolução: Resolvido, tamanho/P

#212 Atualização 1.3.3087
  Core/Backstories/Backstories.xml
  Core/DefInjected/QuestScriptDef/Scripts_JoinerThreatCore.xml
  Core/DefInjected/StatDef/Stats_Basics_General.xml
  Core/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
  Core/DefInjected/WorkTypeDef/WorkTypes.xml
  Core/Keyed/FloatMenu.xml
  Core/Keyed/Messages.xml
Labels: Tipo: Atualização do RimWorld, tamanho/M, Condição: Aguardando Revisão

#213 1.3.3117 Update RimWorld (Royalty + Ideology + Random Improvements)
  .Instalação/GuiaDeInstalação.md
  .Instalação/_update.ps1
  .Notas/scripts/update-wordinfo.sh
  Core/Keyed/Credits.xml
  Core/Keyed/FloatMenu.xml
  Core/Keyed/Misc_Gameplay.xml
  Ideology/DefInjected/HistoryEventDef/Precepts_IdeoDiversity.xml
  Ideology/DefInjected/InteractionDef/Interactions_Speech.xml
  Ideology/DefInjected/IssueDef/Precepts_Lighting.xml
  Ideology/DefInjected/JobDef/Jobs_Gatherings.xml
  Ideology/DefInjected/PreceptDef/Precepts_Lighting.xml
  Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
  Ideology/DefInjected/RitualBehaviorDef/Ritual_Behaviors.xml
  Ideology/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
  Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml
  Ideology/DefInjected/ThingDef/Buildings_Ideo.xml
  Ideology/DefInjected/ThingDef/Buildings_Misc.xml
  Ideology/DefInjected/ThoughtDef/Precepts_IdeoDiversity.xml
  Ideology/DefInjected/ThoughtDef/Precepts_Lighting.xml
  Ideology/Keyed/Alerts.xml
  Ideology/Keyed/Dialogs_Various.xml
  Ideology/Keyed/ITabs.xml
  Ideology/Keyed/Messages.xml
  Ideology/Keyed/Misc_Gameplay.xml
  Royalty/Keyed/Messages.xml
  Royalty/Keyed/Misc_Gameplay.xml
Labels: Tipo: Atualização do RimWorld, Condição: Aguardando Resposta, tamanho/M
