Repository Ludeon/RimWorld-PortugueseBrazilian, pull requests merged in 2022-11, with the labels that each got.

#273 [1.4] - Alteração do termo "Precipitação tóxica" para "Chuva tóxica"
  Core/DefInjected/BackstoryDef/Solid_Child.xml
  Core/DefInjected/GameConditionDef/GameConditions_Misc.xml
  Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml
  Core/DefInjected/TaleDef/Tales_Incident.xml
  Core/Keyed/Menus_Main.xml
  Core/WordInfo/Gender/Singular.txt
  Core/WordInfo/Gender/new_words.txt
  Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
Labels: Tipo: Erro, Tipo: Aprimoramento, tamanho/M, Mesclagem: Squash

#272 1.4 / Core - Backstories: Adult_Tribal & Child_Tribal
  Core/DefInjected/BackstoryDef/Tribal_Adult.xml
  Core/DefInjected/BackstoryDef/Tribal_Child.xml
Labels: Tipo: Aprimoramento, tamanho/P

#277 1.4 / CORE - Reformulação de Backstories: Gambler / Offworld_Medieval…
  Core/DefInjected/BackstoryDef/Gambler_Adult.xml
  Core/DefInjected/BackstoryDef/Gambler_Child.xml
  Core/DefInjected/BackstoryDef/Offworld_Medieval_Adult.xml
  Core/DefInjected/BackstoryDef/Offworld_Medieval_Child.xml
  Core/DefInjected/BackstoryDef/Offworld_Specific_Child.xml
  Core/DefInjected/BackstoryDef/Pirate_Adult.xml
  Core/DefInjected/BackstoryDef/Special.xml
Labels: Tipo: Aprimoramento, Resolução: Resolvido, Tamanho/M
