Repository Ludeon/RimWorld-PortugueseBrazilian, pull requests merged in 2022-03, with the labels that each got.

#232 Atualização na Aba "Trabalho"
  .Instalação/GuiaDeInstalação.md
  Core/DefInjected/SkillDef/Skills.xml
  Core/DefInjected/WorkGiverDef/WorkGivers.xml
  Core/DefInjected/WorkTypeDef/WorkTypes.xml
  Core/Keyed/Menus_Main.xml
  Ideology/DefInjected/WorkGiverDef/WorkGivers.xml
Labels: Tipo: Aprimoramento, tamanho/P, Condição: Aguardando Revisão, Mesclagem: Squash

#234 Atualização do RimWorld: 1.3.3287
  .gitignore
  Core/Backstories/Backstories.xml
  Core/DefInjected/ThingDef/ImpliedDefs.xml
  Core/Keyed/GameplayCommands.xml
  Ideology/DefInjected/HistoryEventDef/Precepts_MeatEating.xml
  Ideology/DefInjected/IdeoPresetCategoryDef/IdeoPresetDefs.xml
  Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
  Ideology/DefInjected/PreceptDef/Precepts_MeatEating.xml
  Ideology/DefInjected/PreceptDef/Precepts_Ranching.xml
  Ideology/DefInjected/RulePackDef/RulePacks_Ritual_Funeral.xml
  Ideology/DefInjected/ThoughtDef/Precepts_MeatEating.xml
  Ideology/DefInjected/ThoughtDef/Precepts_Ranching.xml
  Ideology/Keyed/Alerts.xml
  Ideology/Keyed/Dialogs_Various.xml
  Ideology/Keyed/Messages.xml
  Ideology/Keyed/Misc_Gameplay.xml
Labels: Atenção Requerida, Tipo: Atualização do RimWorld, Condição: Aguardando Resposta, tamanho/M

#233 Atualização 1.3.3287 + Atualização dos Narradores
  Core/Backstories/Backstories.xml
  Core/DefInjected/DifficultyDef/Difficulties.xml
  Core/DefInjected/HairDef/HairsGeneral.xml
  Core/DefInjected/ResearchProjectDef/ResearchProjects_5_Ship.xml
  Core/DefInjected/RulePackDef/RulePacks_Namers_WorldFeatures.xml
  Core/DefInjected/ScenarioDef/Scenarios_Classic.xml
  Core/DefInjected/StorytellerDef/Storytellers.xml
  Core/DefInjected/ThingDef/Buildings_Production.xml
  Core/DefInjected/ThingDef/Buildings_Ship.xml
  Core/DefInjected/ThingDef/ImpliedDefs.xml
  Core/DefInjected/ThingDef/Items_Resource_AnimalProduct.xml
  Core/DefInjected/ThingDef/Plants_Wild_Temperate.xml
  Core/DefInjected/ThoughtDef/Thoughts_Memory_Eating.xml
  Core/Keyed/Alerts.xml
  Core/Keyed/Credits.xml
  Core/Keyed/Dialog_StatsReports.xml
  Core/Keyed/Dialogs_Various.xml
  Core/Keyed/Menu_Options.xml
  Core/Keyed/Menus_Main.xml
  Core/WordInfo/Gender/Singular.txt
  Core/WordInfo/Gender/new_words.txt
  Ideology/DefInjected/InstructionDef/Tutor.xml
  Ideology/Keyed/FloatMenu.xml
  Ideology/Keyed/MainTabs.xml
  Ideology/Keyed/Misc_Gameplay.xml
  Royalty/Keyed/GameplayCommands.xml
Labels: Tipo: Aprimoramento, tamanho/P, Condição: Aguardando Revisão, Mesclagem: Squash

#237 :(
  Core/DefInjected/HistoryAutoRecorderGroupDef/HistoryAutoRecorderGroups.xml
  Core/DefInjected/KeyBindingCategoryDef/ImpliedDefs.xml
  Core/DefInjected/KeyBindingCategoryDef/KeyBindingCategories.xml
  Core/DefInjected/KeyBindingDef/ImpliedDefs.xml
  Core/DefInjected/KeyBindingDef/KeyBindings.xml
  Core/Keyed/MainTabs.xml
  Core/Keyed/Menu_Options.xml
  Core/Keyed/Menus_Main.xml
  Core/Keyed/Messages.xml
  Core/Keyed/Misc_Gameplay.xml
Labels: Tipo: Erro

#238 Pequenas Correções e Modificações
  Core/DefInjected/GameConditionDef/Buildings_Exotic.xml
  Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml
  Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
  Core/DefInjected/MentalStateDef/MentalStates_Special.xml
  Core/DefInjected/RecipeDef/Items_Exotic.xml
  Core/DefInjected/TaleDef/Tales_Incident.xml
  Core/DefInjected/ThingDef/Buildings_Misc.xml
  Core/DefInjected/ThingDef/Hediffs_BodyParts_Bionic.xml
  Core/DefInjected/ThingDef/ImpliedDefs.xml
  Core/DefInjected/ThingDef/Items_Resource_Manufactured.xml
  Core/DefInjected/ThingDef/RangedSpecial.xml
  Core/DefInjected/WorldObjectDef/WorldObjects.xml
  Core/Keyed/Dialogs_Various.xml
  Core/Keyed/FloatMenu.xml
  Core/Keyed/GameplayCommands.xml
  Core/Keyed/Menus_Main.xml
  Core/Keyed/Messages.xml
  Core/Keyed/Misc_Gameplay.xml
  Core/WordInfo/Gender/Singular.txt
  Core/WordInfo/Gender/new_words.txt
  Ideology/DefInjected/MentalStateDef/MentalStates_Mood.xml
  Ideology/DefInjected/MentalStateDef/MentalStates_Special.xml
  Royalty/DefInjected/AbilityDef/Abilities.xml
  Royalty/DefInjected/MentalStateDef/MentalStates_Special.xml
  Royalty/DefInjected/RecipeDef/Hediffs_Local_Misc.xml
  Royalty/DefInjected/RoyalTitlePermitDef/RoyalPermits_Empire.xml
Labels: Tipo: Erro, Tipo: Aprimoramento, tamanho/M, Condição: Aguardando Revisão, Mesclagem: Squash
