Repository Ludeon/RimWorld-PortugueseBrazilian, pull requests merged in 2024-04, with the labels that each got.

#284 BodyDef, ConceptDef, DamageDef, ExpansionDef, HediffDef
  Core/DefInjected/BodyDef/Bodies_Mechanoid.xml
  Core/DefInjected/ConceptDef/Concepts_NotedOpportunistic.xml
  Core/DefInjected/DamageDef/Damages_Misc.xml
  Core/DefInjected/ExpansionDef/ExpansionDefs.xml
  Core/DefInjected/FactionDef/Factions_Hidden.xml
  Core/DefInjected/HediffDef/Hediffs_BodyParts_Bionic.xml
  Core/DefInjected/HediffDef/Hediffs_Debug.xml
  Core/DefInjected/HediffDef/Hediffs_Global_Misc.xml
  Core/DefInjected/HediffDef/Hediffs_Local_Chronic.xml
  Core/DefInjected/HediffDef/Hediffs_Local_Infections.xml
  Core/DefInjected/HediffDef/Hediffs_Local_Injuries.xml
  Core/DefInjected/HediffDef/Hediffs_Local_Misc.xml
  Core/DefInjected/HediffDef/Hediffs_Psycasts.xml
Labels: Tipo: Atualização do RimWorld, Tamanho/M, Condição: Aguardando Revisão

#285 Codificação UTF-8 com BOM
  .Instalação/ScriptDeAtualização.ps1
Labels: Tipo: Erro, Tamanho/PP, Condição: Aguardando Revisão

#286 Tradução inicial para a DLC Anomaly
  Anomaly/DefInjected/BackstoryDef/Solid.xml
  Anomaly/DefInjected/BiomeDef/LabyrinthMapGenerator.xml
  Anomaly/DefInjected/BiomeDef/MetalHellMapGenerator.xml
  Anomaly/DefInjected/BiomeDef/UndercaveMapGenerator.xml
  Anomaly/DefInjected/BodyPartDef/Bodies_Entities.xml
  Anomaly/DefInjected/BodyPartDef/Bodies_Fleshbeasts.xml
  Anomaly/DefInjected/BodyPartGroupDef/Bodies_Entities.xml
  Anomaly/DefInjected/BodyPartGroupDef/Bodies_Fleshbeasts.xml
  Anomaly/DefInjected/BodyPartGroupDef/BodyPartGroups.xml
  Anomaly/DefInjected/DamageDef/Damages_Environmental.xml
  Anomaly/DefInjected/DamageDef/Damages_Misc.xml
  Anomaly/DefInjected/DesignationCategoryDef/DesignationCategories.xml
  Anomaly/DefInjected/EntityCategoryDef/EntityCategories.xml
Labels: Tipo: Aprimoramento, Tipo: Atualização do RimWorld, Resolução: Resolvido, Tamanho/P

#287 Tradução para a DLC Anomality, Interações e Missões
  Anomaly/DefInjected/InteractionDef/Interactions_Misc.xml
  Anomaly/DefInjected/QuestScriptDef/Script_CreepjoinerJoins.xml
  Anomaly/DefInjected/QuestScriptDef/Script_DistressCall.xml
  Anomaly/DefInjected/QuestScriptDef/Script_EndGame_VoidAwakening.xml
  Anomaly/DefInjected/QuestScriptDef/Script_MonolithMigration.xml
  Anomaly/DefInjected/QuestScriptDef/Script_MysteriousCargo.xml
  Anomaly/DefInjected/QuestScriptDef/Script_SightstealerArrival.xml
  Anomaly/DefInjected/QuestScriptDef/Script_TransportPodCrash_Ghoul.xml
  Anomaly/DefInjected/QuestScriptDef/Script_UnnaturalDarkness.xml
  Anomaly/DefInjected/RulePackDef/Interactions_Misc.xml
Labels: Tipo: Atualização do RimWorld, Condição: Aguardando Resposta, Tamanho/M, Mesclagem: Squash

#288 Continuação na tradução da DLC Anomaly
  Anomaly/DefInjected/EntityCategoryDef/EntityCategories.xml
  Anomaly/DefInjected/FactionDef/Factions_Misc.xml
  Anomaly/DefInjected/FactionDef/Factions_Player.xml
  Anomaly/DefInjected/HairDef/HairsGhoul.xml
  Anomaly/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
  Anomaly/DefInjected/InfectionPathwayDef/InfectionPathwayDefs.xml
  Anomaly/DefInjected/IssueDef/Precepts_Inhumanizing.xml
  Anomaly/DefInjected/IssueDef/Precepts_PsychicRituals.xml
  Anomaly/DefInjected/IssueDef/Precepts_VoidStudy.xml
  Anomaly/DefInjected/JobDef/Jobs_Work.xml
  Anomaly/DefInjected/KnowledgeCategoryDef/KnowledgeCategories.xml
  Anomaly/DefInjected/MapGeneratorDef/LabyrinthMapGenerator.xml
  Anomaly/DefInjected/MapGeneratorDef/MetalHellMapGenerator.xml
  Anomaly/DefInjected/MapGeneratorDef/UndercaveMapGenerator.xml
  Anomaly/DefInjected/MeditationFocusDef/MeditationFocusDefs.xml
  Anomaly/DefInjected/MentalBreakDef/MentalStates_Mood.xml
  Anomaly/DefInjected/MentalBreakDef/MentalStates_Special.xml
  Anomaly/DefInjected/PawnKindDef/PawnKinds_Mutants.xml
  Anomaly/DefInjected/PawnKindDef/PawnKinds_Player.xml
  Anomaly/DefInjected/PawnRenderTreeDef/PawnRenderTreeDefs.xml
  Anomaly/DefInjected/PsychicRitualRoleDef/PsychicRitualRoles.xml
  Anomaly/DefInjected/RecordDef/Records_Misc.xml
  Anomaly/DefInjected/RoofDef/Roofs.xml
  Anomaly/DefInjected/RoomRoleDef/RoomRoles.xml
  Anomaly/DefInjected/ScenPartDef/ScenParts_Various.xml
  Anomaly/DefInjected/StatCategoryDef/Stats_Containment.xml
  Anomaly/DefInjected/StatCategoryDef/Stats_PsychicRituals.xml
  Anomaly/DefInjected/StatCategoryDef/Stats_Serum.xml
  Anomaly/DefInjected/StuffCategoryDef/StuffCategories.xml
  Anomaly/DefInjected/StyleCategoryDef/StyleCategoryDefs.xml
  Anomaly/DefInjected/StyleItemCategoryDef/HairsCultist.xml
  Anomaly/DefInjected/ThingCategoryDef/ThingCategories.xml
Labels: Tipo: Aprimoramento, Tipo: Atualização do RimWorld, Tamanho/M, Condição: Aguardando Revisão

#293 Tradução do Menu de Configurações da 1.5
  Core/Keyed/Enums.xml
  Core/Keyed/Menu_Options.xml
Labels: Tipo: Atualização do RimWorld, Resolução: Resolvido, Tamanho/PP

#297 Tradução da DLC Anomaly, HabilityDef/Entidades e Corpos
  .Instalação/ScriptDeAtualização.ps1
  Anomaly/DefInjected/AbilityDef/Abilities.xml
  Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
  Anomaly/DefInjected/BodyDef/Bodies_Entities.xml
  Anomaly/DefInjected/BodyDef/Bodies_Fleshbeasts.xml
Labels: Tipo: Atualização do RimWorld, Resolução: Resolvido, Tamanho/G, Mesclagem: Squash

#301 Tradução da DLC Anomaly, StatDef, PreceptDef e PrisonerInteractionModeDef
  Anomaly/DefInjected/PreceptDef/Precepts_Inhumanizing.xml
  Anomaly/DefInjected/PreceptDef/Precepts_PsychicRituals.xml
  Anomaly/DefInjected/PreceptDef/Precepts_VoidStudy.xml
  Anomaly/DefInjected/PrisonerInteractionModeDef/PrisonerInteractionModeDefs.xml
  Anomaly/DefInjected/StatDef/Stats_Containment.xml
  Anomaly/DefInjected/StatDef/Stats_Pawns_Misc.xml
  Anomaly/DefInjected/StatDef/Stats_PsychicRituals.xml
Labels: Tipo: Atualização do RimWorld, Resolução: Resolvido, Tamanho/M, Mesclagem: Squash

#309 Hotfix, Erro nas Configurações
  Core/Keyed/Menu_Options.xml
Labels: Tipo: Erro, Tamanho/PP, Condição: Aguardando Revisão

#308 Tradução da DLC Anomaly, MemeDef
  Anomaly/DefInjected/MemeDef/Memes_Misc.xml
  Anomaly/DefInjected/ResearchProjectDef/ResearchProjects_Anomaly.xml
Labels: Tipo: Erro, Tipo: Atualização do RimWorld, Resolução: Resolvido, Tamanho/P, Mesclagem: Squash

#300 Tradução da DLC Anomaly, ConceptDef/Tutor
  Anomaly/DefInjected/ConceptDef/Tutor.xml
Labels: Tipo: Atualização do RimWorld, Tamanho/P
